# Generated by Django 2.0 on 2017-12-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czynnosc',
            name='met',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
